### PR TITLE
Update port to new 9668

### PR DESCRIPTION
**Pull request by MalloZup**
see https://github.com/prometheus/prometheus/wiki/Default-port-allocations

### CODE REVIEW

**Comment by diegoakechi** [comment]
@MalloZup please check why the checks are not passing...

**Comment by MalloZup** [comment]
@diegoakechi thx checking

**Comment by diegoakechi** [comment]
There is a typo in one of the port numberd

**Comment by MalloZup** [comment]
already fixed

**Comment by diegoakechi** [comment]
@MalloZup Please create a package version change and include an entry on the changelog, otherwise it will not be submitted to OBS.

**Comment by MalloZup** [comment]
@diegoakechi ok

**Pull request merged**
