### PR TITLE
Filter invalid tenants data on multitenant usage

### PR DESCRIPTION
**Pull request by arbulu89**
For some reason the query we use to get the SQL port of the tenants can return some rows with 0 as value.
In order to avoid the usage of these invalid ports this change will omit the connection of these values.

image

### CODE REVIEW

**Comment by diegoakechi** [comment]
@xarbulu, wouldn't be simpler change the query to filter the ports not equal to 0 on the query?

**Comment by arbulu89** [comment]
> @xarbulu, wouldn't be simpler change the query to filter the ports not equal to 0 on the query?

Not for me as I'm not a big fan of SQL hehe.
How would it be? Like this?:
```
SELECT DATABASE_NAME,SQL_PORT FROM SYS_DATABASES.M_SERVICES WHERE COORDINATOR_TYPE='MASTER' and SQL_PORT!=0; 
```

**Comment by diegoakechi** [comment]
@xarbulu, yes, basically that =). I would only recommend to use `<>` instead of `!=` to be ISO complaint, but both should work. I didn't check if the column is numeric or varchar, but if it gives you an error, you will need to convert 0 to `0`.

**Comment by arbulu89** [comment]
The `SQL_PORT` value is an Integer.
image

**Pull request merged**
